### ISSUE TITLE
No OAuth on dashboard

### ISSUE THREAD

**Issue by jabowery** [iexcloud/iexcloud-openid-client-example#5]
The "walkthrough" directs one to use OAuth but it isn't on my dashboard.  If there is a prerequisite please indicate what it is.
![image](https://user-images.githubusercontent.com/57646/111082422-298e6e00-84d6-11eb-99aa-70baf775cb8e.png)

**Comment by ghost** [comment]
https://iexcloud.io/docs/api/#oauth-oidc-beta

**Comment by ghost** [comment]
@jabowery I should clarify, it will be visible once we have enough oauth apps in prod that people are actually authorizing
